### ISSUE TITLE
HELM 3 Catalog Enhancement - filter charts based on kubeVersion of cluster

### ISSUE THREAD

**Issue by morstad** [openshift/enhancements#224]
Utilize [kubeVersion field](https://helm.sh/docs/topics/charts/#the-kubeversion-field) from helm index to filter charts which are NOT supported on current cluster.  

Excerpt from helm index with 'kubeVersion:'  : 
```
apiVersion: v1
entries:
  chart-a:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-02-21T17:06:07.641831254-05:00"
    dependencies:
    - alias: sch
      name: ibm-sch
      repository: '@sch'
      version: 1.2.6
    description: Chart for deploying product a
    digest: 4a71450835d18c2bee431d15a10096ce085f2d024b49067e41ede31bb8893818
    keywords:
    - example
    kubeVersion: '>=1.11.0'
    name: chart-a
    urls:
    - chart-a-3.1.0.tgz
    version: 3.1.0
```

@sbose78 @siamaksade @pedjak
